version: '3.9'
services:
  kitty-chan-events:
    build: .

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - kitty-chan-events
    ports:
      - 5000:5000