version: "3.9"
services:
  kittychan:
    build: .
    image: kittychan-domain
    container_name: kittychan-domain
    ports:
      - "5011:5000"
    networks:
    - kittychan-network

networks:
  kittychan-network:
    name: kittychan-network