version: "3.9"
services:
  kittychan:
    build: .
    image: kittychan-domain
    container_name: kittychan-domain
    networks:
    - kittychan-network
    restart: always

networks:
  kittychan-network:
    name: kittychan-network