version: "3.9"
services:
  kittychan:
    build: .
    container_name: kittychan
    ports:
      - "5000:5000"
    depends_on:
      - redis
    restart: always
  
  redis:
    image: redis
    container_name: kittychan-events-redis
    restart: always
    env_file:
      - .env
    command: "redis-server --requirepass ${REDIS_PASS}"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  